/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import homeTheater.HomeTheaterFacade;

/**
 *
 * @author anthony
 */
public class GraphicPlayer extends javax.swing.JFrame {
    
    HomeTheaterFacade htf;
    int type;

    /**
     * Creates new form ClientPlayer
     */
    public GraphicPlayer() {
        initComponents();
    }
    
    public GraphicPlayer(HomeTheaterFacade htf) {
        initComponents();
        this.htf = htf;
        this.setVisible(true);
        this.setVolume(this.htf.getVolume());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientSelection = new javax.swing.ButtonGroup();
        cdRadioBtn = new javax.swing.JRadioButton();
        dvdRadioBtn = new javax.swing.JRadioButton();
        tunerRadioBtn = new javax.swing.JRadioButton();
        playBtn = new javax.swing.JButton();
        pauseBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        feedbackLabel = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        volumeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientSelection.add(cdRadioBtn);
        cdRadioBtn.setText("CD");
        cdRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdRadioBtnActionPerformed(evt);
            }
        });

        clientSelection.add(dvdRadioBtn);
        dvdRadioBtn.setText("DVD");
        dvdRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvdRadioBtnActionPerformed(evt);
            }
        });

        clientSelection.add(tunerRadioBtn);
        tunerRadioBtn.setText("Tuner");
        tunerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunerRadioBtnActionPerformed(evt);
            }
        });

        playBtn.setText("Play");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        pauseBtn.setText("Pause");
        pauseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseBtnActionPerformed(evt);
            }
        });

        stopBtn.setText("Stop");
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        feedbackLabel.setText("Welcome to your Player, please make your choice !");

        jToggleButton1.setText("+");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("-");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        volumeLabel.setText("Volume 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(playBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pauseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feedbackLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(volumeLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdRadioBtn)
                            .addComponent(dvdRadioBtn)
                            .addComponent(tunerRadioBtn))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cdRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dvdRadioBtn)
                    .addComponent(feedbackLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tunerRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(playBtn)
                                    .addComponent(pauseBtn)
                                    .addComponent(stopBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(volumeLabel)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdRadioBtnActionPerformed
        this.type = HomeTheaterFacade.MediaType_Music;
        NewDiskDialog ndd = new NewDiskDialog(this,true);
        ndd.setMaterial("Record");
        ndd.setName("Artist");
    }//GEN-LAST:event_cdRadioBtnActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        switch (this.type) {
            case HomeTheaterFacade.MediaType_Music:
                this.feedbackLabel.setText(this.htf.listenCD());
                break;
            case HomeTheaterFacade.MediaType_Movie:
                this.feedbackLabel.setText(this.htf.watchMovie());
                break;
            case HomeTheaterFacade.MediaType_Tuner:
                this.feedbackLabel.setText(this.htf.listenRadio());
                break;
            default:
                break;
        }
    }//GEN-LAST:event_playBtnActionPerformed

    private void dvdRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvdRadioBtnActionPerformed
        this.type = HomeTheaterFacade.MediaType_Movie;
        NewDiskDialog ndd = new NewDiskDialog(this,true);
        ndd.setMaterial("Movie");
        ndd.setName("Realisator");
        
    }//GEN-LAST:event_dvdRadioBtnActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.setVolume(this.htf.upVolume());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        this.setVolume(this.htf.downVolume());
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void tunerRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunerRadioBtnActionPerformed
        this.type = HomeTheaterFacade.MediaType_Tuner;
        TunerFreqDialog tfd = new TunerFreqDialog(this,true);
    }//GEN-LAST:event_tunerRadioBtnActionPerformed

    private void pauseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseBtnActionPerformed
        switch (this.type) {
            case HomeTheaterFacade.MediaType_Music:
                this.feedbackLabel.setText(this.htf.pauseCD());
                break;
            case HomeTheaterFacade.MediaType_Movie:
                this.feedbackLabel.setText(this.htf.pauseMovie());
                break;
            default:
                break;
        }
    }//GEN-LAST:event_pauseBtnActionPerformed

    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        switch (this.type) {
            case HomeTheaterFacade.MediaType_Music:
                this.feedbackLabel.setText(this.htf.endCD());
                break;
            case HomeTheaterFacade.MediaType_Movie:
                this.feedbackLabel.setText(this.htf.endMovie());
                break;
            case HomeTheaterFacade.MediaType_Tuner:
                this.feedbackLabel.setText(this.htf.endTuner());
                break;
            default:
                break;
        }
    }//GEN-LAST:event_stopBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicPlayer().setVisible(true);
            }
        });
    }
    
    public void setVolume(int vol){
        this.volumeLabel.setText(String.valueOf(vol));
    }
    
    public void setFeedback(String fb){
        this.feedbackLabel.setText(fb);
    }

    public HomeTheaterFacade getHtf() {
        return htf;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cdRadioBtn;
    private javax.swing.ButtonGroup clientSelection;
    private javax.swing.JRadioButton dvdRadioBtn;
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton pauseBtn;
    private javax.swing.JButton playBtn;
    private javax.swing.JButton stopBtn;
    private javax.swing.JRadioButton tunerRadioBtn;
    private javax.swing.JLabel volumeLabel;
    // End of variables declaration//GEN-END:variables
}
